"""empty message

Revision ID: 942a17c8c44e
Revises: 
Create Date: 2017-02-18 21:06:19.062345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '942a17c8c44e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kampuswerkout', sa.Column('hand', sa.String(length=4096), nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung1', sa.Integer(), nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung2', sa.Integer(), nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung3', sa.Integer(), nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung4', sa.Integer(), nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung5', sa.Integer(), nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung6', sa.Integer(), nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung7', sa.Integer(), nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung8', sa.Integer(), nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung9', sa.Integer(), nullable=True))
    op.drop_column('kampuswerkout', 'kampuslog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kampuswerkout', sa.Column('kampuslog', mysql.VARCHAR(length=4096), nullable=True))
    op.drop_column('kampuswerkout', 'rung9')
    op.drop_column('kampuswerkout', 'rung8')
    op.drop_column('kampuswerkout', 'rung7')
    op.drop_column('kampuswerkout', 'rung6')
    op.drop_column('kampuswerkout', 'rung5')
    op.drop_column('kampuswerkout', 'rung4')
    op.drop_column('kampuswerkout', 'rung3')
    op.drop_column('kampuswerkout', 'rung2')
    op.drop_column('kampuswerkout', 'rung1')
    op.drop_column('kampuswerkout', 'hand')
    # ### end Alembic commands ###
