"""empty message

Revision ID: a587af522417
Revises: 942a17c8c44e
Create Date: 2017-02-19 15:15:41.595252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a587af522417'
down_revision = '942a17c8c44e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kampuswerkout', sa.Column('kampuslog', sa.String(length=4096), nullable=True))
    op.drop_column('kampuswerkout', 'rung7')
    op.drop_column('kampuswerkout', 'rung6')
    op.drop_column('kampuswerkout', 'rung1')
    op.drop_column('kampuswerkout', 'hand')
    op.drop_column('kampuswerkout', 'rung2')
    op.drop_column('kampuswerkout', 'rung5')
    op.drop_column('kampuswerkout', 'rung8')
    op.drop_column('kampuswerkout', 'rung9')
    op.drop_column('kampuswerkout', 'rung4')
    op.drop_column('kampuswerkout', 'rung3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kampuswerkout', sa.Column('rung3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung4', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung9', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung8', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung5', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('kampuswerkout', sa.Column('hand', mysql.VARCHAR(length=4096), nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung6', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('kampuswerkout', sa.Column('rung7', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('kampuswerkout', 'kampuslog')
    # ### end Alembic commands ###
