"""empty message

Revision ID: cced1c633483
Revises: 
Create Date: 2017-02-21 00:08:26.293328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cced1c633483'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    op.create_table('blocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4096), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('werktime', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=96), nullable=True),
    sa.Column('venue', sa.String(length=96), nullable=True),
    sa.Column('angle', sa.String(length=96), nullable=True),
    sa.Column('style', sa.String(length=96), nullable=True),
    sa.Column('comments', sa.String(length=4096), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bodyweight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4096), nullable=True),
    sa.Column('bodyweight_kg', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=4096), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circuitmoves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4096), nullable=True),
    sa.Column('numberofmoves', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('werktime', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=4096), nullable=True),
    sa.Column('comments', sa.String(length=4096), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hangboardwerk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4096), nullable=True),
    sa.Column('board', sa.String(length=96), nullable=True),
    sa.Column('holds_used', sa.Integer(), nullable=True),
    sa.Column('arm_used', sa.String(length=96), nullable=True),
    sa.Column('hangtime', sa.Integer(), nullable=True),
    sa.Column('resttime', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('setrest', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kampuswerkout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4096), nullable=True),
    sa.Column('kampuslog', sa.String(length=4096), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4096), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('werktime', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=96), nullable=True),
    sa.Column('venue', sa.String(length=96), nullable=True),
    sa.Column('angle', sa.String(length=96), nullable=True),
    sa.Column('style', sa.String(length=96), nullable=True),
    sa.Column('comments', sa.String(length=4096), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    op.drop_table('kampuswerkout')
    op.drop_table('hangboardwerk')
    op.drop_table('circuitmoves')
    op.drop_table('bodyweight')
    op.drop_table('blocs')
    op.drop_table('users')
    # ### end Alembic commands ###
