"""empty message

Revision ID: f17958f385c5
Revises: b7bbcab83d69
Create Date: 2017-02-19 20:22:56.601632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17958f385c5'
down_revision = 'b7bbcab83d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hangboardwerk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4096), nullable=True),
    sa.Column('holds_used', sa.Integer(), nullable=True),
    sa.Column('arm_used', sa.String(length=96), nullable=True),
    sa.Column('hangtime', sa.Integer(), nullable=True),
    sa.Column('resttime', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('setrest', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hangboardwerk')
    # ### end Alembic commands ###
